### ISSUE TITLE
Refactor app

### ISSUE THREAD

**Issue by korikuzma** [GenomicMedLab/cool-seq-tool#157]

**Comment by jsstevenson** [comment]
Not sure if a refactor is the place to do it, but it'd be great to distinguish between "errors" (which prevent the return of any meaningful data, and can be raised as exceptions) and "warnings" (which could be like an asterisk accompanying a successful response -- as in, "here is the data you asked for, but as a warning, there could've been another correct answer too"). It might trim code length/complexity if we can reduce the number of places where we handle length-2 tuples instead of direct return values.

**Comment by korikuzma** [comment]
> Not sure if a refactor is the place to do it, but it'd be great to distinguish between "errors" (which prevent the return of any meaningful data, and can be raised as exceptions) and "warnings" (which could be like an asterisk accompanying a successful response -- as in, "here is the data you asked for, but as a warning, there could've been another correct answer too"). It might trim code length/complexity if we can reduce the number of places where we handle length-2 tuples instead of direct return values.

Ya, I've kind of been using the two terms interchangeably to mean errors but agree that we need better handling in all of our apps. In VarCat, I made the change to raise exceptions in the backend rather than returning tuple (which is sadly what I'm doing in a variation normalizer issue haha).

**Comment by jsstevenson** [comment]
+1 for closing, we can address more specific tasks in other issues
