### ISSUE TITLE
Use Gene Normalizer class initialization tools/methods

### ISSUE THREAD

**Issue by jsstevenson** [GenomicMedLab/cool-seq-tool#187]
To avoid repeating ourselves (and save some documentation effort) we should just use QueryHandler/database initialization methods directly from Gene Normalizer instead of defining specific params like `db_url`. (pending https://github.com/cancervariants/gene-normalization/issues/235)

**Comment by korikuzma** [comment]
@jsstevenson so are you proposing just having users set the environment variables? 

One reason why we did the ddb instantiation is because it was done before [this](https://github.com/cancervariants/gene-normalization/pull/193) issue. Now that it's fixed, I agree with using the create_db function so people can use ddb or postgres

**Comment by jsstevenson** [comment]
Something like that, yeah? Mostly I think the fewer hard-coded interface elements we have that get passed down to other libraries, the better. Maybe pass through any **kwargs to a constructor method, but otherwise just let the Gene Normalizer be in charge of things like checking env vars, etc.

**Comment by korikuzma** [comment]
That works for me. I got rid of allowing params to be passed for cool-seq-tool paths in variation normalizer. Can you make this same issue in variation-normalizer + (probably) metakb?

**Comment by korikuzma** [comment]
#196 is removing gene normalizer
