### ISSUE TITLE
Add start/end residue mode parameter

### ISSUE THREAD

**Issue by korikuzma** [GenomicMedLab/cool-seq-tool#330]
### Feature description

Currently, `residue_mode` is used to describe the input positions residue mode. We should add an end residue mode parameter.

### Use case

In [this](https://github.com/cancervariants/variation-normalization/pull/575#pullrequestreview-2199934897) Variation Normalizer PR, I had to do a hacky +1 since `g_to_grch38` returns inter-residue mode but we need residue mode at this step. It would be nice to specify the end residue mode needed.

### Contribution

None

**Comment by jsstevenson** [comment]
We're a ways out from this, but I think it'd be nice to start thinking about API consistency throughout CST -- rather than adding an extra argument to optionally alter the output coordinate mode here, I wonder if there are more generic ways to handle this for all functions that return positions (maybe a decorator?)

**Comment by korikuzma** [comment]
After conversations, I think I should revisit this in Variation Normalizer and not add additional complexity / confusion in Cool-Seq-Tool. We also want people to use inter-residue coordinates, so this would help enforce this. I'm going to close. We can re-open if this is actually needed.
